# permissions for end users to edit knativefunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: knativefunction-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devconf-knative-operator
    app.kubernetes.io/part-of: devconf-knative-operator
    app.kubernetes.io/managed-by: kustomize
  name: knativefunction-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - knativefunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - knativefunctions/status
  verbs:
  - get
