---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - knf.example.com
  resources:
  - knativefunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knf.example.com
  resources:
  - knativefunctions/finalizers
  verbs:
  - update
- apiGroups:
  - knf.example.com
  resources:
  - knativefunctions/status
  verbs:
  - get
  - patch
  - update
